<html:select property="provincia" size="1">
	<html:option value="Alava"/>
	<html:option value="Albacete"/>
	<html:option value="Alicante"/>
	<html:option value="Almeria"/>
	<html:option value="Asturias"/>
	<html:option value="Avila"/>
	<html:option value="Badajoz"/>
	<html:option value="Barcelona"/>
	<html:option value="Burgos"/>
	<html:option value="Caceres"/>
	<html:option value="Cadiz"/>
	<html:option value="Cantabria"/>
	<html:option value="Castellon"/>
	<html:option value="Ciudad Real"/>
	<html:option value="Cordoba"/>	
	<html:option value="Cuenca"/>
	<html:option value="Gerona"/>
	<html:option value="Granada"/>
	<html:option value="Guadalajara"/>
	<html:option value="Guipuzcua"/>
	<html:option value="Huelva"/>
	<html:option value="Huesca"/>
	<html:option value="Ibiza-Formentera"/>
	<html:option value="La Coruña"/>
	<html:option value="La Rioja"/>
	<html:option value="Las Palmas"/>
	<html:option value="Leon"/>
	<html:option value="Lerida"/>
	<html:option value="Lugo"/>
	<html:option value="Madrid"/>
	<html:option value="Malaga"/>
	<html:option value="Mayorca"/>
	<html:option value="Menorca"/>
	<html:option value="Murcia"/>
	<html:option value="Navarra"/>
	<html:option value="Orense"/>
	<html:option value="Palencia"/>
	<html:option value="Pontevedra"/>
	<html:option value="Salamanca"/>
	<html:option value="Santa Cruz de Tenerife"/>
	<html:option value="Segobia"/>
	<html:option value="Sevilla"/>	
	<html:option value="Soria"/>
	<html:option value="Tarragona"/>
	<html:option value="Teruel"/>
	<html:option value="Toledo"/>
	<html:option value="Valencia"/>		
	<html:option value="Valladolid"/>
	<html:option value="Vizcaya"/>
	<html:option value="Zamora"/>
	<html:option value="Zaragoza"/>
</html:select>
<html:errors property="provincia" />